### ISSUE TITLE
core_utils.serialization

### ISSUE THREAD

**Issue by sjungz** [kareem-metwaly/glidenet#3]
Hi I tried to install something correspond to core_utils, but I cannot find one. Where can I find it?

**Comment by kareem-metwaly** [comment]
Hi, as mentioned in the README:

> The code has previously used some proprietary packages during my internship at [Scale AI](https://scale.com/). Therefore, these packages are missing here, which breaks the code. However, in models/glidenet.py, you can find the complete implemented structure of GlideNet. You can use configs/models/car/glidenet.yaml for example to play with the configuration of the architecture.

feel free to reopen if you have further info
