### ISSUE TITLE
Regarding the 2022 CVPR paper "GlideNet: Global, Local and Intrinsic based Dense Embedding NETwork for Multi-category Attributes Prediction", please consult

### ISSUE THREAD

**Issue by zxx1218** [kareem-metwaly/glidenet#4]
Hello author, I am a graduate student in the Department of Computer Science at Huzhou University. I recently read your paper on CVPR titled GlideNet: Global, Local, and Intrinsic based Dense Embedding Network for Multi category Attributes Prediction. I attempted to reproduce the code provided in the paper, but as you mentioned in readme, I used a self-developed package in the code, so I was unable to debug it. I would like to inquire if it is possible to provide me with the missing package in my paper, or if it is possible to run the code correctly in the absence of a package.

We look forward to your reply
thank you !

**Comment by kareem-metwaly** [comment]
Unfortunately, the missing files are Scale's proprietary and they are closed-source. However, the missing files are related to training and logging which are not actually very special in the case of GlideNet and it is possible to implement them by yourself. Let me know if you have a specific question about something and I will try and answer it.
