### ISSUE TITLE
I have a question that I would like to consult with you.

### ISSUE THREAD

**Issue by xuyaozh** [kareem-metwaly/glidenet#5]
Hello, author. I recently read your paper on CVPR titled GlideNet: A Global, Local, and Intrinsic Dense Embedding Network for Multiclass Attribute Prediction. I tried to reproduce the code provided in the paper, but during the reproduction, I encountered an error where the name 'CategorizationTask' in utils. py in the dataset/car folder is not defined. May I ask what this is?
Looking forward to your reply.
thank you.

**Comment by kareem-metwaly** [comment]
I was using the class "CategorizationTask" when I'm fetching the dataset from the ScaleAPI. This is not needed now.
You can ignore the methods from_task and from_subtask as you won't be able to fetch the dataset from the ScaleAPI.
I will close this for now but let me know if you have further questions.
